# Generated by Django 4.1 on 2022-08-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_payments', '0003_alter_deposite_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='deposite_amount',
            field=models.CharField(default=0.0, max_length=50, verbose_name='total deposite amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='widthdrawl_amount',
            field=models.CharField(default=0.0, max_length=50, verbose_name='total withdrawl amount'),
        ),
    ]
