# Generated by Django 4.1 on 2022-09-02 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all_payments', '0004_alter_transaction_deposite_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='withdraw_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=50, verbose_name='Account Holder name')),
                ('is_withdrawl', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawl request',
                'verbose_name_plural': 'Withdrawl request',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
