# Generated by Django 4.1 on 2022-09-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_payments', '0005_withdraw_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdraw_request',
            options={'managed': True, 'verbose_name': 'Withdrawal request', 'verbose_name_plural': 'Withdrawal request'},
        ),
        migrations.RenameField(
            model_name='withdraw_request',
            old_name='Type',
            new_name='type',
        ),
    ]
