# Generated by Django 4.1 on 2022-09-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_payments', '0006_alter_withdraw_request_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposite_request',
            name='is_accpted',
            field=models.BooleanField(default=False),
        ),
         migrations.AddField(
            model_name='deposite_request',
            name='request_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
