# Generated by Django 4.1 on 2022-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_payments', '0007_deposite_request_is_accpted'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw_request',
            name='is_accpted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdraw_request',
            name='equest_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
