# Generated by Django 4.1 on 2022-09-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_payments', '0008_withdraw_request_is_accpted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw_request',
            old_name='equest_at',
            new_name='request_at',
        ),
        migrations.AlterField(
            model_name='withdraw_request',
            name='account_holder',
            field=models.CharField(max_length=50, verbose_name='Account Holder Number'),
        ),
    ]
