# Generated by Django 4.1 on 2022-08-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage_animated_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animated_line', models.CharField(help_text='please enter text which moving in Home page', max_length=500, verbose_name='Animated Line')),
            ],
        ),
    ]
