# Generated by Django 4.1 on 2022-09-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'All user statement',
                'verbose_name_plural': 'All user statement',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
