# Generated by Django 4.1 on 2022-09-03 03:32
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0002_user_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_game_statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=50)),
                ('playing_time', models.DateTimeField(auto_now_add=True)),
                ('stake', models.CharField(max_length=50)),
                ('Luck_stake', models.CharField(max_length=50)),
                ('Amount', models.CharField(max_length=50)),
                ('Rate', models.CharField(max_length=50)),
                ('Return_Amount', models.FloatField()),
                ('Win_Lose', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'All user game statement',
                'verbose_name_plural': 'All user game statement',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='User_statement',
        ),
    ]
